- action:
  - data:
      entity_id: media_player.spotify
      source: Ares
    service: media_player.select_source
  - delay: '10'
  - data:
      entity_id: media_player.spotify
      media_content_id: spotify:user:icehot94:playlist:44Q7We1ZcaRhIOMghcEs4a
      media_content_type: playlist
    service: media_player.play_media
  - data:
      entity_id: media_player.spotify
      shuffle: 'true'
    service: media_player.shuffle_set
  - data:
      entity_id: media_player.spotify
    service: media_player.media_next_track
  alias: Good morning
  condition:
  - condition: state
    entity_id: device_tracker.zeus_zeus
    state: home
  - after: 07:59
    before: '12:01'
    condition: time
  id: '1508734891497'
  trigger:
  - entity_id: binary_sensor.alarm
    platform: state
    to: 'on'
- action:
  - data_template:
      entity_id: media_player.spotify
      volume_level: '{{  states.input_number.spotify_volume.state  }}'
    service: media_player.volume_set
  alias: Set Spotify Volume
  condition: []
  id: '14589756321469'
  trigger:
    platform: state
    entity_id: input_number.spotify_volume
- action:
  - data:
      message: There is an update to Homeassistant
    service: notify.notify_my_android
  alias: New Hass
  condition: []
  id: '1509009509367'
  trigger:
  - entity_id: updater.updater
    platform: state
- action:
  - data:
      name: darkorange
    service: frontend.set_theme
  alias: Hass Color
  condition: []
  id: '1510513414834'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data:
      entity_id: light.living_room
      white_value: 200
    service: light.turn_on
  alias: Got Home
  condition:
  - after: 08:00
    before: '23:59'
    condition: time
  - after: sunset
    condition: sun
  id: '1511270584828'
  trigger:
  - entity_id: device_tracker.zeus_zeus
    platform: state
    to: home
- action:
  - data:
      entity_id: light.living_room
    service: light.turn_off
  alias: Going Out
  condition:
  - after: 08:00
    before: '23:59'
    condition: time
  id: '1519586676399'
  trigger:
  - entity_id: device_tracker.zeus_zeus
    from: home
    platform: state
- action:
  - data:
      brightness_pct: 60
      entity_id: light.living_room
      kelvin: 2500
    service: light.turn_on
  alias: Sunset
  condition:
  - condition: state
    entity_id: device_tracker.zeus_zeus
    state: home
  id: '1521231654786'
  trigger:
  - event: sunset
    offset: -00:30:00
    platform: sun
- action:
  - data:
      entity_id: light.living_room
      flash: long
    service: light.turn_on
  alias: Low battery
  condition:
  - condition: state
    entity_id: device_tracker.zeus_zeus
    state: home
  id: '1521234495237'
  trigger:
  - below: '20'
    entity_id: sensor.phonebatt
    platform: numeric_state
- action:
  - data:
      entity_id: light.living_room
    service: light.turn_off
  alias: Movie Time
  condition: []
  id: '1521562752133'
  trigger:
  - entity_id: media_player.ares_2
    platform: state
    to: playing
  - entity_id: media_player.ares_2
    platform: state
    to: playing
- action:
  - data:
      brightness_pct: 50
      entity_id: light.living_room
    service: light.turn_on
  alias: Movie Paused/Stopped
  condition: []
  id: '1521580166378'
  trigger:
  - entity_id: media_player.ares_2
    platform: state
    to: paused
  - entity_id: media_player.ares_2
    platform: state
    to: idle
- action: []
  alias: Motion
  condition:
  - condition: state
    entity_id: device_tracker.zeus_zeus
    state: away
  id: '1521603770293'
  trigger:
  - entity_id: sensor.motion
    platform: state
    to: 'on'
