- action:
  - data:
      entity_id: media_player.spotify
      source: Ares
    service: media_player.select_source
  - delay: '10'
  - data:
      entity_id: media_player.spotify
      media_content_id: spotify:user:icehot94:playlist:44Q7We1ZcaRhIOMghcEs4a
      media_content_type: playlist
    service: media_player.play_media
  - data:
      entity_id: media_player.spotify
      shuffle: 'true'
    service: media_player.shuffle_set
  - data:
      entity_id: media_player.spotify
    service: media_player.media_next_track
  alias: Good morning
  condition:
  - condition: state
    entity_id: device_tracker.zeus_zeus
    state: home
  - after: 07:59
    before: '12:01'
    condition: time
  id: '1508734891497'
  trigger:
  - entity_id: binary_sensor.alarm
    platform: state
    to: 'on'
- action:
  - data_template:
      entity_id: media_player.spotify
      volume_level: '{{  states.input_number.spotify_volume.state  }}'
    service: media_player.volume_set
  alias: Set Spotify Volume
  condition: []
  id: '14589756321469'
  trigger:
    platform: state
    entity_id: input_number.spotify_volume
- id: '1509009509367'
  alias: New Hass
  trigger:
  - entity_id: updater.updater
    platform: state
  condition: []
  action:
  - data:
      message: There is an update to Homeassistant
    service: notify.slack
- id: '1510513414834'
  alias: Hass Color
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: darkcyan
    service: frontend.set_theme
- id: '1511270584828'
  alias: Living Room - Motion
  trigger:
  - entity_id: sensor.living_room_motion
    platform: state
    to: '1'
  condition:
  - after: 07:00
    before: '23:00'
    condition: time
  action:
  - data:
      brightness_pct: 50
      entity_id: light.living_room
      white_value: 200
    service: light.turn_on
- action:
  - data:
      entity_id: light.living_room
    service: light.turn_off
  alias: Movie Time
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  id: '1521562752133'
  trigger:
  - entity_id: media_player.ares_2
    from: idle
    platform: state
    to: playing
  - entity_id: media_player.ares_2
    from: paused
    platform: state
    to: playing
- action:
  - data:
      brightness_pct: 50
      entity_id: light.living_room
    service: light.turn_on
  alias: Movie Paused/Stopped
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  id: '1521580166378'
  trigger:
  - entity_id: media_player.ares_2
    from: playing
    platform: state
    to: paused
  - entity_id: media_player.ares_2
    from: playing
    platform: state
    to: idle
- action:
  - data:
      entity_id: light.living_room
      flash: long
    service: light.turn_on
  alias: Morpheus Signal
  condition:
  - condition: state
    entity_id: device_tracker.zeus_zeus
    state: home
  id: '1521763621943'
  trigger:
  - entity_id: binary_sensor.down
    platform: state
    to: 'on'
- id: '1522970955759'
  alias: Hallway - Motion
  trigger:
  - entity_id: sensor.hallway_motion
    platform: state
    to: '1'
  condition:
  - after: 07:00
    before: '23:00'
    condition: time
  action:
  - data:
      brightness_pct: 50
      entity_id: light.hallway
    service: light.turn_on
- id: '1530577811492'
  alias: Hallway - Late Night Motion
  trigger:
  - entity_id: sensor.hallway_motion
    platform: state
    to: '1'
  condition:
  - after: '23:00'
    before: 07:00
    condition: time
  action:
  - data:
      brightness_pct: 5
      entity_id: light.hallway
      white_value: 20
    service: light.turn_on
- id: '1534771487128'
  alias: Hallway - Turn off
  trigger:
  - entity_id: sensor.hallway_motion
    for:
      minutes: 1
    platform: state
    to: '0'
  condition: []
  action:
  - data:
      entity_id: light.hallway
    service: light.turn_off
- id: '1534792238847'
  alias: Living Room - Late Night Motion
  trigger:
  - entity_id: sensor.living_room_motion
    platform: state
    to: '1'
  condition:
  - after: '23:00'
    before: 07:00
    condition: time
  action:
  - data:
      brightness_pct: 5
      entity_id: light.living_room
      white_value: 20
    service: light.turn_on
- id: '1534792309228'
  alias: Living Room - Turn off
  trigger:
  - entity_id: sensor.living_room_motion
    for:
      minutes: 20
    platform: state
    to: '0'
  action:
  - data:
      entity_id: light.living_room
    service: light.turn_off
- id: '1538468416706'
  alias: Season Changer
  trigger:
  - entity_id: sensor.season
    from: Winter
    platform: state
    to: Spring
  - entity_id: sensor.season
    from: Spring
    platform: state
    to: Summer
  - entity_id: sensor.season
    from: Summer
    platform: state
    to: Fall
  - entity_id: sensor.season
    from: Fall
    platform: state
    to: Winter
  condition: []
  action:
  - data:
      message: The seasons have changed!
    service: notify.slack
