- action:
  - data:
      entity_id: media_player.spotify
      source: Ares
    service: media_player.select_source
  - delay: '10'
  - data:
      entity_id: media_player.spotify
      media_content_id: spotify:user:icehot94:playlist:44Q7We1ZcaRhIOMghcEs4a
      media_content_type: playlist
    service: media_player.play_media
  - data:
      entity_id: media_player.spotify
    service: media_player.play_media
  - data:
      entity_id: media_player.spotify
      shuffle: 'true'
    service: media_player.shuffle_set
  - data:
      entity_id: media_player.spotify
    service: media_player.media_next_track
  alias: Spotify in ze morgen
  condition:
  - condition: state
    entity_id: device_tracker.zeus_zeus
    state: home
  id: '1508734891497'
  trigger:
  - at: 09:00
    platform: time
- action:
  - data_template:
      entity_id: media_player.spotify
      volume_level: '{{  states.input_number.spotify_volume.state  }}'
    service: media_player.volume_set
  alias: Set Spotify Volume
  condition: []
  id: '14589756321469'
  trigger:
    platform: state
    entity_id: input_number.spotify_volume
- action:
  - alias: "Smsa att jag \xE4r framme"
    data:
      event: At_Whaleoak
      value1: "Framme, kan du \xF6ppna??"
    service: ifttt.trigger
  alias: SMS Location
  condition: []
  id: '1508958838169'
  trigger:
  - entity_id: device_tracker.zeus_zeus
    platform: state
    to: Whaleoak
