- id: '1508734891497'
  alias: Good morning
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == state_attr(''input_datetime.alarm'',
      ''timestamp'') | timestamp_custom(''%H:%M'', false) }}'
  condition:
  - condition: state
    entity_id: device_tracker.zeus_router
    state: home
  - condition: state
    entity_id: input_boolean.alarmstatus
    state: 'on'
  action:
  - data:
      entity_id: switch.hades
    service: switch.turn_on
  - delay: '300'
  - data:
      entity_id: switch.kitchen_plug
    service: switch.turn_on
  - service: script.spotify_alarm
  - data:
      entity_id: input_boolean.sleeping
    service: input_boolean.turn_off
- id: '1510513414834'
  alias: Hass Color
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      name: darkcyan
    service: frontend.set_theme
- id: '1521562752133'
  alias: Movie Time
  trigger:
  - entity_id: sensor.plex_sensor
    platform: state
    to: Playing
  action:
  - data:
      entity_id: light.living_room
    service: light.turn_off
- id: '1521580166378'
  alias: Movie Paused/Stopped
  trigger:
  - entity_id: sensor.plex_sensor
    from: Playing
    platform: state
  condition:
  - below: '5000'
    condition: numeric_state
    entity_id: sensor.living_room_light
  action:
  - data:
      entity_id: light.living_room
    service: light.turn_on
- action:
  - data:
      entity_id: light.living_room
      flash: long
    service: light.turn_on
  alias: Morpheus Signal
  condition:
  - condition: state
    entity_id: device_tracker.zeus_zeus
    state: home
  id: '1521763621943'
  trigger:
  - entity_id: binary_sensor.down
    platform: state
    to: 'on'
- id: '1539475234169'
  alias: 'Cold outside '
  trigger:
  - at: 08:00
    platform: time
  condition:
  - above: '0'
    below: '10'
    condition: numeric_state
    entity_id: sensor.yr_temperature
  action:
  - data:
      message: Det kommer vara kallt idag!
      target:
      - channel/anethass
    service: notify.pushbullet
- id: '15394723545239'
  alias: Rocket Launch
  trigger:
  - platform: template
    value_template: '{{ (now().strftime("%s") | int + 600) == (states.sensor.spacex.state
      | int) }}'
  condition:
  - condition: time
    after: 07:00
    before: '23:00'
  action:
  - service: notify.pushbullet
    data:
      target:
      - channel/anethass
      message: "SPACEX LAUNCH STARTS IN 10 MIN ══════════════════════════ \n\nMission:\
        \ {{ states('sensor.spacex_next_mission_name') }} \n  │\n  ├─ Time: .. {{\
        \ states('sensor.spacex_next_launch_time') }}\n  ├─ Rocket: ..... {{ states('sensor.spacex_next_rocket')\
        \ }}\n  └─ Site: ........... {{ states('sensor.spacex_next_launch_site') }}\n\
        \  \n"
- id: '15394359658439'
  alias: Testing Webhooks
  trigger:
    platform: webhook
    webhook_id: testingwebhooks
  action:
  - service_template: '{{ trigger.json[''service''] }}'
    data_template:
      message: '{{ trigger.json[''data''][''message''] }}'
      target:
      - '{{ trigger.json[''data''][''target''] }}'
- id: '1542146430171'
  alias: Tea off
  trigger:
  - entity_id: switch.kitchen_plug
    platform: state
    to: 'on'
  condition: []
  action:
  - delay: '300'
  - data:
      entity_id: switch.kitchen_plug
    service: switch.turn_off
