- id: '1508734891497'
  alias: Good morning
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == state_attr(''input_datetime.alarm'',
      ''timestamp'') | timestamp_custom(''%H:%M'', false) }}'
  condition:
  - condition: state
    entity_id: device_tracker.zeus_router
    state: home
  - condition: state
    entity_id: input_boolean.alarmstatus
    state: 'on'
  action:
  - service: script.spotify_alarm
- id: '1510513414834'
  alias: Hass Color
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      name: darkcyan
    service: frontend.set_theme
- id: '1521562752133'
  alias: Movie Time
  trigger:
  - platform: webhook
    webhook_id: plex_playing_on_ares
  action:
  - data: {}
    service: light.turn_off
    target:
      area_id: 57fc0aad19fc42c0b787a9fc69de0d7c
  - data:
      entity_id: input_boolean.plex
    service: input_boolean.turn_on
  mode: single
- id: '1521580166378'
  alias: Movie Paused/Stopped
  trigger:
  - platform: webhook
    webhook_id: plex_not_playing_on_ares
  condition: []
  action:
  - data:
      entity_id: input_boolean.plex
    service: input_boolean.turn_off
- action:
  - data:
      entity_id: light.living_room
      flash: long
    service: light.turn_on
  alias: Morpheus Signal
  condition:
  - condition: state
    entity_id: device_tracker.zeus_zeus
    state: home
  id: '1521763621943'
  trigger:
  - entity_id: binary_sensor.down
    platform: state
    to: 'on'
- id: '1539475234169'
  alias: Morning Stuff
  trigger:
  - at: 07:00
    platform: time
  condition: []
  action:
  - data:
      message: '{{states(''sensor.season_checker'')}} and {{states(''sensor.yr_temperature'')}}'
      target:
      - channel/anethass
    service: notify.pushbullet
- id: '15394723545239'
  alias: Rocket Launch
  trigger:
  - platform: template
    value_template: '{{ (now().strftime("%s") | int + 600) == (states.sensor.spacex.state
      | int) }}'
  condition:
  - condition: time
    after: 07:00
    before: '23:00'
  action:
  - service: notify.pushbullet
    data:
      target:
      - channel/anethass
      message: "SPACEX LAUNCH STARTS IN 10 MIN ══════════════════════════ \n\nMission:\
        \ {{ states('sensor.spacex_next_mission_name') }} \n  │\n  ├─ Time: .. {{\
        \ states('sensor.spacex_next_launch_time') }}\n  ├─ Rocket: ..... {{ states('sensor.spacex_next_rocket')\
        \ }}\n  └─ Site: ........... {{ states('sensor.spacex_next_launch_site') }}\n\
        \  \n"
- id: '15394359658439'
  alias: Testing Webhooks
  trigger:
    platform: webhook
    webhook_id: testingwebhooks
  action:
  - service_template: '{{ trigger.json[''service''] }}'
    data_template:
      message: '{{ trigger.json[''data''][''message''] }}'
      target:
      - '{{ trigger.json[''data''][''target''] }}'
- id: '1542146430171'
  alias: Tea off
  trigger:
  - platform: state
    entity_id: switch.flakt
    from: 'off'
    to: 'on'
    for: '900'
  condition: []
  action:
  - data:
      entity_id: switch.flakt
    service: switch.turn_off
  mode: single
- id: '1550503526651'
  alias: Turn on light if movie paused/stopped
  trigger:
  - entity_id: input_boolean.plex
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - below: '5000'
    condition: numeric_state
    entity_id: sensor.living_room_light
  action:
  - data: {}
    service: light.turn_on
    target:
      area_id: 57fc0aad19fc42c0b787a9fc69de0d7c
  mode: single
- id: '1559662126741'
  alias: Pungsvett
  trigger:
  - entity_id: device_tracker.oneplus_6t
    platform: state
    to: home
  condition:
  - above: '21.5'
    condition: numeric_state
    entity_id: sensor.living_room_temperature
  action:
  - data:
      entity_id: switch.kitchen_plug
    service: switch.turn_on
- id: '1570693945128'
  alias: ANet Cert
  description: ''
  trigger:
  - entity_id: sensor.anet
    platform: state
    to: '1'
  condition: []
  action:
  - data:
      message: Certificate is expiring
    service: notify.pushbullet
- id: '1583170491497'
  alias: Streaming off
  description: ''
  trigger:
  - entity_id: device_tracker.apollo
    from: home
    platform: state
  condition:
  - condition: state
    entity_id: input_boolean.streaming
    state: 'on'
  action:
  - data:
      entity_id: input_boolean.streaming
    service: input_boolean.turn_off
- id: '1594925769079'
  alias: Intruders
  description: ''
  trigger:
  - entity_id: sensor.hallway_motion
    from: '0'
    platform: state
    to: '1'
  condition:
  - condition: state
    entity_id: device_tracker.apollo
    state: not_home
  action:
  - data:
      media_content_id: spotify:playlist:1nDx9nvAuW7WYiRxHaSZBS
    service: spotify.play_playlist
  - data:
      entity_id: media_player.spotify
      source: HADES
    service: media_player.select_source
- id: '1597361292566'
  alias: Fläkt kväll
  description: ''
  trigger: []
  condition: []
  action:
  - data:
      entity_id: switch.kitchen_plug
    service: switch.turn_on
  - delay: '600'
  - data:
      entity_id: switch.kitchen_plug
    service: switch.turn_off
- id: '1607607235030'
  alias: Grön RGB
  description: ''
  trigger:
  - hours: '*'
    minutes: '*'
    platform: time_pattern
    seconds: '1'
  condition: []
  action:
  - delay: '1'
  - data:
      color_name: green
      entity_id: light.extended_color_light_1
    service: light.turn_on
- id: '1607607428561'
  alias: Röd RGB
  description: ''
  trigger:
  - hours: '*'
    minutes: '*'
    platform: time_pattern
    seconds: '3'
  condition: []
  action:
  - data:
      color_name: red
      entity_id: light.extended_color_light_1
    service: light.turn_on
