- id: '1508734891497'
  alias: Good morning
  trigger:
  - entity_id: binary_sensor.alarm
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: device_tracker.zeus_zeus
    state: home
  action:
  - data:
      entity_id: media_player.spotify
      source: Shield
    service: media_player.select_source
  - delay: '10'
  - data:
      entity_id: media_player.spotify
      media_content_id: spotify:user:icehot94:playlist:44Q7We1ZcaRhIOMghcEs4a
      media_content_type: playlist
    service: media_player.play_media
  - data:
      entity_id: media_player.spotify
      shuffle: 'true'
    service: media_player.shuffle_set
  - data:
      entity_id: media_player.spotify
    service: media_player.media_next_track
  - data:
      entity_id: switch.hades
    service: switch.turn_on
- id: '1509009509367'
  alias: New Hass
  trigger:
  - entity_id: updater.updater
    platform: state
  action:
  - data:
      message: There is an update to Homeassistant
    service: notify.pushbullet
- id: '1510513414834'
  alias: Hass Color
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      name: darkcyan
    service: frontend.set_theme
- id: '1511270584828'
  alias: Living Room - Motion
  trigger:
  - entity_id: sensor.living_room_motion
    platform: state
    to: '1'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '07:00'
      before: '23:00'
    - condition: template
      value_template: "{{ not is_state('sensor.plex_sensor', 'Playing') }}"
  action:
  - data:
      brightness_pct: 50
      entity_id: light.living_room
      white_value: 200
    service: light.turn_on
- id: '1521562752133'
  alias: Movie Time
  trigger:
  - entity_id: sensor.plex_sensor
    platform: state
    to: Playing
  action:
  - data:
      entity_id: light.living_room
    service: light.turn_off
- id: '1521580166378'
  alias: Movie Paused/Stopped
  trigger:
  - entity_id: sensor.plex_sensor
    from: Playing
    platform: state
  condition:
  - below: '5000'
    condition: numeric_state
    entity_id: sensor.living_room_light
  action:
  - data:
      entity_id: light.living_room
    service: light.turn_on
- action:
  - data:
      entity_id: light.living_room
      flash: long
    service: light.turn_on
  alias: Morpheus Signal
  condition:
  - condition: state
    entity_id: device_tracker.zeus_zeus
    state: home
  id: '1521763621943'
  trigger:
  - entity_id: binary_sensor.down
    platform: state
    to: 'on'
- id: '1522970955759'
  alias: Hallway - Motion
  trigger:
  - entity_id: sensor.hallway_motion
    platform: state
    to: '1'
  condition:
  - after: 07:00
    before: '23:00'
    condition: time
  action:
  - data:
      brightness_pct: 50
      entity_id: light.hallway
    service: light.turn_on
- id: '1530577811492'
  alias: Hallway - Late Night Motion
  trigger:
  - entity_id: sensor.hallway_motion
    platform: state
    to: '1'
  condition:
  - after: '23:00'
    before: 07:00
    condition: time
  action:
  - data:
      brightness_pct: 5
      entity_id: light.hallway
      white_value: 20
    service: light.turn_on
- id: '1534771487128'
  alias: Hallway - Turn off
  trigger:
  - entity_id: sensor.hallway_motion
    for:
      minutes: 1
    platform: state
    to: '0'
  condition: []
  action:
  - data:
      entity_id: light.hallway
    service: light.turn_off
- id: '1534792238847'
  alias: Living Room - Late Night Motion
  trigger:
  - entity_id: sensor.living_room_motion
    platform: state
    to: '1'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '23:00'
      before: 07:00
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.plex_sensor
        state: Stopped
      - condition: state
        entity_id: sensor.plex_sensor
        state: Paused
  action:
  - data:
      brightness_pct: 5
      entity_id: light.living_room
      white_value: 20
    service: light.turn_on
- id: '1534792309228'
  alias: Living Room - Turn off
  trigger:
  - entity_id: sensor.living_room_motion
    for:
      minutes: 20
    platform: state
    to: '0'
  action:
  - data:
      entity_id: light.living_room
    service: light.turn_off
- id: '1534792709238'
  alias: Living Room - Dim
  trigger:
  - entity_id: sensor.living_room_motion
    for:
      minutes: 15
    platform: state
    to: '0'
  action:
  - data:
      brightness_pct: 5
      entity_id: light.living_room
      white_value: 20
    service: light.turn_on
- id: '1538468416706'
  alias: Season Changer
  trigger:
  - entity_id: sensor.season
    platform: state
  action:
  - data:
      message: The seasons have changed!
    service: notify.pushbullet
- id: '1535465419796'
  alias: Spotify Volume (Set)
  trigger:
  - platform: state
    entity_id: input_number.spotify_volume
  action:
  - service: media_player.volume_set
    data_template:
      entity_id: media_player.spotify
      volume_level: '{{  states.input_number.spotify_volume.state | int / 100  }}'
- id: '1538465419706'
  alias: Spotify Volume (Sync)
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.spotify_volume
  action:
  - delay: 5
  - service: input_number.set_value
    data_template:
      entity_id: input_number.spotify_volume
      value: '{{  states.sensor.spotify_volume.state | float | round(2) * 100  }}'
- id: '1536468406706'
  alias: Spotify Shuffle (Set)
  trigger:
  - platform: state
    entity_id: input_boolean.spotify_shuffle
  action:
  - service: media_player.shuffle_set
    data_template:
      entity_id: media_player.spotify
      shuffle: '{% if is_state(''input_boolean.spotify_shuffle'', ''off'') %}  false
        {% elif is_state(''input_boolean.spotify_shuffle'', ''on'') %} true {% endif
        %}

        '
- id: '1538464416707'
  alias: Spotify Shuffle (Sync)
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.spotify_shuffle
  action:
  - delay: 5
  - service_template: "{% if states.sensor.spotify_shuffle.state == 'False' %}\n \
      \ input_boolean.turn_off\n{% else %}\n  input_boolean.turn_on\n{% endif %}\n"
    data:
      entity_id: input_boolean.spotify_shuffle
- id: '1538468416706'
  alias: Spotify Source (Sync)
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.spotify_source
  action:
  - service: input_select.select_option
    entity_id: input_select.spotify_source
    data_template:
      option: '{{  states.sensor.spotify_source.state  }}'
- id: '1538268416766'
  alias: Alarm
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.input_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: input_boolean.alarmstatus
    state: 'on'
  action:
  - data:
      entity_id: media_player.spotify
      source: Ares
    service: media_player.select_source
  - data:
      entity_id: media_player.spotify
      shuffle: 'true'
    service: media_player.shuffle_set
  - data:
      entity_id: media_player.spotify
      volume_level: '0.3'
    service: media_player.volume_set
  - data:
      entity_id: media_player.spotify
      media_content_id: spotify:user:icehot94:playlist:2ZZUYCryHU5g22zaSOuAug
      media_content_type: playlist
    service: media_player.play_media
- id: '1539475234169'
  alias: 'Cold outside '
  trigger:
  - at: 08:00
    platform: time
  condition:
  - above: '0'
    below: '10'
    condition: numeric_state
    entity_id: sensor.yr_temperature
  action:
  - data:
      message: Det kommer vara kallt idag!
      target:
      - channel/anethass
    service: notify.pushbullet
- id: '1539475958239'
  alias: Motion at home
  trigger:
  - entity_id: sensor.hallway_motion
    from: '0'
    platform: state
    to: '1'
  - entity_id: sensor.living_room_motion
    from: '0'
    platform: state
    to: '1'
  condition:
  - condition: state
    entity_id: device_tracker.zeus
    state: not_home
  action:
  - data:
      message: There is motion at home!
      target:
      - channel/anethass
    service: notify.pushbullet
- id: '15394723545239'
  alias: Rocket Launch
  trigger:
  - platform: template
    value_template: '{{ (now().strftime("%s") | int + 600) == (states.sensor.spacex.state | int) }}'
  condition:
  - condition: time
    after: '07:00'
    before: '23:00'
    #condition: time
  action:
  - service: notify.pushbullet
    data:
      target:
      - channel/anethass
      message: >
        SPACEX LAUNCH STARTS IN 10 MIN
        ══════════════════════════ 


        Mission: {{ states('sensor.spacex_next_mission_name') }} 
          │
          ├─ Time: .. {{ states('sensor.spacex_next_launch_time') }}
          ├─ Rocket: ..... {{ states('sensor.spacex_next_rocket') }}
          └─ Site: ........... {{ states('sensor.spacex_next_launch_site') }}
          

- id: '15394359658439'
  alias: Testing Webhooks
  trigger:
    platform: webhook
    webhook_id: testingwebhooks
  action:
  - service_template: "{{ trigger.json['service'] }}"
    data_template:
      message: "{{ trigger.json['data']['message'] }}"
      target:
      - "{{ trigger.json['data']['target'] }}"