homeassistant:
  # Name of the location where Home Assistant is running
  name: Poseidon
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 54
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  #Apply random customizations
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

#Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zones.yaml
device_tracker: !include device_tracker.yaml
frontend: !include frontend.yaml


#Add IFTTT functionality
ifttt:
  key: !secret ifttt_key

#Enable map in HA
map:

#mqtt:
#  broker: !secret mqtt_broker
#  port: !secret mqtt_port
#  client_id: Hass
#  keepalive: 60
#  username: !secret mqtt_user
#  password: !secret mqtt_pass


# Enables configuration UI
config:

#Config for HA SSL and password
http:
  api_password: !secret http_password
  base_url: 192.168.5.2:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

#Sliders and input boxes
input_number:
#Slider for controling Spotify volume
  spotify_volume:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05
    mode: slider

#Dropdown lists
input_select:
#Dropdown list of Spotify playlists
  spotify_playlist:
    name: 'Playlist:'
    options:
      - Wildcard
      - Youthish
      - Fekke
    icon: mdi:spotify
#Dropdown list of Spotify sources
  spotify_source:
    name: 'Source:'
    options:
      - Hades
      - Ares
    #initial: Ares
    icon: mdi:speaker-wireless

#Diffrent media-players
media_player:
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret
    cashe_path: /home/homeassistant/.homeassistant/.spotify-token-cashe

  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    scan_interval: 2
    show_all_controls: true
    use_custom_entity_ids: true
    use_episode_art: true


#Send notifications from HA to Slack and other services
notify:
  - name: Slack
    platform: slack
    api_key: !secret slack_key
    default_channel: '#anet-testing'
  - name: "Notify My Android"
    platform: nma
    api_key: !secret nma_key

mqtt:
  broker: 192.168.5.2
  port: 1883

wake_on_lan:

switch:
  #WoL
  - platform: wake_on_lan
    mac_address: !secret hades-mac
    host: Hades
    name: "Hades"
    turn_off: 
      service: shell_command.turn_off_hades

shell_command:
    turn_off_hades: ssh avdag@Hades shutdown -s -t 10

#Google Assistant
google_assistant:
  project_id: !secret project_id 
  client_id: !secret google_id
  access_token: !secret google_token
  exposed_domains:
   - switch
   #- light
   #- media_player

camera:
  - platform: generic
    name: weather
    still_image_url: https://www.yr.no/sted/Sverige/%C3%96sterg%C3%B6tland/Link%C3%B6ping/meteogram.svg
    content_type: 'image/svg+xml'
#  - platform: mjpeg
#    name: Hallway
#    mjpeg_url: http://rollei:rolleipw@192.168.5.92/videostream.cgi?user=rollei&pwd=rolleipw&resolution=32&rate=0 