homeassistant:
  # Name of the location where Home Assistant is running
  name: Poseidon
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 54
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  #Apply random customizations
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /home/xr34ct/scripts/misc/data
    - /etc/avdagic.net/pics
  

# Show links to resources in log and frontend
#introduction:

#Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zones.yaml
device_tracker: !include device_tracker.yaml
frontend: !include frontend.yaml


#Add IFTTT functionality
ifttt:
  key: !secret ifttt_key

#Enable map in HA
map:

#mqtt:
#  broker: !secret mqtt_broker
#  port: !secret mqtt_port
#  client_id: Hass
#  keepalive: 60
#  username: !secret mqtt_user
#  password: !secret mqtt_pass


# Enables configuration UI
config:

#Config for HA SSL and password
http:
  api_password: !secret http_password
  base_url: https://192.168.5.2:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

weather:
  - platform: yweather
#    woeid: 897380

input_boolean:
  weather:
  spotify_shuffle:
    name: Shuffle
    icon: mdi:shuffle-variant
  alarmstatus:
    name: Primed!
    initial: off
    icon: mdi:alarm-check

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

#Sliders and input boxes
input_number:
#Slider for controling Spotify volume
  spotify_volume:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 100
    step: 1
  alarm_time_h:
    name: Hour
    icon: mdi:timer
    initial: 0
    min: 0
    max: 23
    unit_of_measurement: h
    mode: box
  alarm_time_m:
    name: Minute
    icon: mdi:timer
    initial: 0
    min: 0
    max: 59
    unit_of_measurement: min
    mode: box
    
#Dropdown lists
input_select:
#Dropdown list of Spotify playlists
  spotify_playlist:
    name: 'Playlist:'
    options:
      - Wildcard
      - Youthish
      - Fekke
      - Germanium
    icon: mdi:spotify
#Dropdown list of Spotify sources
  spotify_source:
    name: 'Source:'
    options:
      - HADES
      - Ares
    #initial: Ares
    icon: mdi:speaker-wireless

hue:
  bridges:
    - host: 192.168.5.150

#Diffrent media-players
media_player:
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret
    cashe_path: /home/homeassistant/.homeassistant/.spotify-token-cashe

  - platform: plex
    entity_namespace: 'plex'
#    include_non_clients: true
    scan_interval: 1
    show_all_controls: true
#    use_custom_entity_ids: false
#    use_episode_art: true


#Send notifications from HA to Slack and other services
notify:
  - name: Slack
    platform: slack
    api_key: !secret slack_key
    default_channel: '#anet-testing'
#  - name: "Notify My Android"
#    platform: nma
#    api_key: !secret nma_key
  - name: Push
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

mqtt:
  broker: 192.168.5.2
  port: 1883

wake_on_lan:

switch:
  #WoL
  - platform: wake_on_lan
    mac_address: !secret hades-mac
    host: Hades
    name: "Hades"
    turn_off: 
      service: shell_command.turn_off_hades

shell_command:
    turn_off_hades: ssh avdag@Hades shutdown -s -t 10

#Google Assistant
google_assistant:
  project_id: !secret project_id 
  client_id: !secret google_id
  access_token: !secret google_token
  api_key: !secret google_api_key
  exposed_domains:
   - switch
   #- light
   #- media_player

   
input_datetime:
  input_time:
    name: Alarm Input
    has_date: false
    has_time: true

camera:
  - platform: generic
    name: yr
    still_image_url: https://www.yr.no/sted/Sverige/%C3%96sterg%C3%B6tland/Link%C3%B6ping/meteogram.svg
    content_type: 'image/svg+xml'
#  - platform: mjpeg
#    name: Hallway
#    mjpeg_url: http://rollei:rolleipw@192.168.5.92/videostream.cgi?user=rollei&pwd=rolleipw&resolution=32&rate=0 


