homeassistant:
  # Name of the location where Home Assistant is running
  name: Poseidon
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 54
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  #Apply random customizations
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /home/xr34ct/scripts/misc/data
    - /etc/avdagic.net
  

# Show links to resources in log and frontend
#introduction:

#Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zones.yaml
device_tracker: !include device_tracker.yaml
frontend: !include frontend.yaml

system_health:
#mobile_app:
person:

lovelace:
  mode: yaml
  
#Add IFTTT functionality
ifttt:
  key: !secret ifttt_key

#Enable map in HA
map:

# mqtt:
  # broker: !secret mqtt_broker
  # port: !secret mqtt_port
  # client_id: hass
  # keepalive: 60
  # username: !secret mqtt_user
  # password: !secret mqtt_pass


# Enables configuration UI
config:

#Config for HA SSL and password
# http:
#   #api_password: !secret http_password
#   #base_url: http://192.168.5.2:8123
#   base_url: https://hass.avdagic.net

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# custom_updater:
#   card_urls:
#     - https://raw.githubusercontent.com/sgttrs/lovelace-weather-card-chart/master/custom-updater.json

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

asuswrt:
  host: 192.168.5.1
  username: !secret router_user
  password: !secret router_pass
  #track_new_devices: false

weather:
#  - platform: yweather
#    woeid: 897380
  - platform: openweathermap
    api_key: !secret openweathermap
    mode: hourly
    name: hourly_owm
  - platform: openweathermap
    api_key: !secret openweathermap
    mode: freedaily
    name: daily_owm

input_boolean:
  weather:
  spotify_shuffle:
    name: Shuffle
    icon: mdi:shuffle-variant
  alarmstatus:
    name: Primed!
    initial: off
    icon: mdi:alarm-check
  sleeping:
    name: True if sleeping
    initial: off
  streaming:
    name: Streaming
    initial: off
  plex:
    name: Plex on Ares
    initial: off
  hjuul:
    name: RGB Hjuul
    initial: off

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

#Sliders and input boxes
input_number:
#Slider for controling Spotify volume
  spotify_volume:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 100
    step: 1
    
#Dropdown lists
input_select:
#Dropdown list of Spotify playlists
  spotify_playlist:
    name: 'Playlist:'
    options:
      - Wildcard
      - Youthish
      - Fekke
      - Germanium
    icon: mdi:spotify
#Dropdown list of Spotify sources
  spotify_source:
    name: 'Source:'
    options:
      - HADES
      - Ares
      - Zeus
      - Slappenz
    #initial: Ares
    icon: mdi:speaker-wireless

hue:
  bridges:
    - host: 192.168.5.150

#Diffrent media-players
media_player:
  - platform: spotify
    scan_interval: 5
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret
#    cashe_path: /home/homeassistant/.homeassistant/.spotify-token-cashe

  - platform: plex
    entity_namespace: 'plex'
#    include_non_clients: true
    scan_interval: 1
#    show_all_controls: true
#    use_custom_entity_ids: false
#    use_episode_art: true


#Send notifications from HA to Slack and other services
notify:
  - name: Slack
    platform: slack
    api_key: !secret slack_key
    default_channel: '#anet-testing'
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api
#  - name: matrix
#    platform: matrix
#    default_room: "#hass-testing:avdagic.net"
#  - name: Push
#    platform: html5
#    gcm_api_key: !secret gcm_api_key
#    gcm_sender_id: !secret gcm_sender_id

# mqtt:
  # broker: 192.168.5.2
  # port: 1883

wake_on_lan:

# switch:
#   #WoL
#   - platform: wake_on_lan
#     mac_address: !secret hades-mac
#     host: Hades
#     name: "Hades"
#     turn_off: 
#       service: shell_command.turn_off_hades
      
#  - platform: tplink
#    host: 192.168.5.184
    
  

shell_command:
    turn_off_hades: ssh "Mr. Classified"@Hades shutdown -s -t 10

#Google Assistant
google_assistant:
  project_id: !secret project_id 
  #client_id: !secret google_id
  #access_token: !secret google_token
  api_key: !secret google_api_key
  exposed_domains:
    - switch
    - input_boolean
    
   #- light
   #- media_player

   
input_datetime:
  alarm:
    name: Alarm Input
    has_date: false
    has_time: true
  season_date:
    name: Season started on
    has_date: true
    has_time: false

camera:
  - platform: generic
    name: yr
    still_image_url: https://www.yr.no/sted/Sverige/%C3%96sterg%C3%B6tland/Link%C3%B6ping/meteogram.svg
    content_type: 'image/svg+xml'
#  - platform: mjpeg
#    name: Hallway
#    mjpeg_url: http://rollei:rolleipw@192.168.5.92/videostream.cgi?user=rollei&pwd=rolleipw&resolution=32&rate=0 

#matrix:
#  homeserver: https://avdagic.net
#  username: "@hass:avdagic.net"
#  password: !secret matrix_pw
#  rooms:
#    - "#hass-testing:avdagic.net"
#transmission:
#  host: 192.168.5.2
#  username: !secret transmission_user
#  password: !secret transmission_pass
#  scan_interval: 30
#  monitored_conditions:
#    - current_status
#    - download_speed
#    - upload_speed
#    - active_torrents
#    - paused_torrents
#    - total_torrents
#    - started_torrents
#    - completed_torrents
  
speedtestdotnet:
