# Weather prediction
- platform: yr
  monitored_conditions:
    - temperature
    - humidity

#Check remaining dayts on certificate
- platform: cert_expiry
  host: avdagic.net
  name: ANet

# Plex Activiy
- platform: plex
  host: 192.168.5.2
  username: !secret plex_user
  password: !secret plex_pass

#Current Version
- platform: version

#Check uptime
- platform: uptime
