# Weather prediction
- platform: yr
  monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature

#Check remaining dayts on certificate
- platform: cert_expiry
  host: avdagic.net
  name: ANet

# Plex Activiy
- platform: plex
  host: 192.168.5.2
  username: !secret plex_user
  password: !secret plex_pass

#Current Version
- platform: version

#Check uptime
- platform: uptime

#Speed
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

#Netdata
- platform: netdata
  resources:
    - memory_free
    - memory_used
    - system_load
    - disk_free
    - cpu_iowait
    - cpu_user
    - cpu_system

#Motion
- platform: mqtt
  state_topic: "homeassistant/motion"
  name: "Motion"