# Weather prediction
- platform: yr
  monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
- platform: file
  file_path: /scripts/misc/data/season.txt
  name: Season

#Check remaining dayts on certificate
- platform: cert_expiry
  host: avdagic.net
  name: ANet

# Plex Activiy
#- platform: plex
#  host: 192.168.5.2
#  username: !secret plex_user
#  password: !secret plex_pass

#Current Version
- platform: version

#Check uptime
- platform: uptime

#Speed
- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

#Netdata
#- platform: netdata
#  resources:
#    "System CPU":
#      data_group: system.cpu
#      element: system
#    "IOWait":
#      data_group: system.cpu
#      element: iowait
#    "User":
#       data_group: system.cpu:
#       element: user
#    system.load:
#      element: load15
#      name: "Load 15"
#    system.ram:
#      element: free
#      name: "Free RAM"
#    system.ram:
#      element: used
#    disk_space._:
#      element: avail
#      name: "Boot Drive"
#    disk_space._media_4khdr:
#      element: avail
#      name: "4K & HDR"
#    disk_space._media_srv:
#      element: avail
#      name: "Server"

#    - memory_free
#    - memory_used
#    - system_load
#    - disk_free
#    - cpu_iowait
#    - cpu_user
#    - cpu_system

#Hue
- platform: rest
  resource: !secret hallway_temp
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Hallway Temperature'
- platform: rest
  resource: !secret hallway_lux
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Hallway Light'
- platform: rest
  resource: !secret hallway_motion
  value_template: '{{ value_json.state.status }}'
  name: 'Hallway Motion'
  scan_interval: 0.1
- platform: rest
  resource: !secret livingroom_temp
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Living Room Temperature'
- platform: rest
  resource: !secret livingroom_lux
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Living Room Light'
- platform: rest
  resource: !secret livingroom_motion
  value_template: '{{ value_json.state.status }}'
  name: 'Living Room Motion'
  scan_interval: 0.1
  
#Spotify
- platform: template
  sensors:
    spotify_volume:
      friendly_name: "Spotify Volume"
      value_template: "{{ states.media_player.spotify.attributes.volume_level }}"
- platform: template
  sensors:
    spotify_shuffle:
      friendly_name: "Spotify Shuffle"
      value_template: "{{ states.media_player.spotify.attributes.shuffle }}"
- platform: template
  sensors:
    spotify_source:
      friendly_name: "Spotify Source"
      value_template: "{{ states.media_player.spotify.attributes.source }}"
      
#Alarm
- platform: template
  sensors:
    alarm_time:
      friendly_name: 'Time'
      value_template: '{{ states.input_slider.alarm_time_h.state }}:{{ states.input_slider.alarm_time_m.state }}'
#Time Sensor      
- platform: time_date
  display_options:
  - 'time'
