title: ANet Homeassistant
# Include external resources
resources:
#  - url: /local/my-custom-card.js
#    type: js
#  - url: /local/my-webfont.css
#    type: css
#  - url: /local/custom_ui/weather-card.js
#    type: js
  - url: /local/group-card/group-card.js
    type: js
  - url: /local/button-card/button-card.js
    type: module
  - type: module
    url: /local/custom_ui/custom-weather-card-chart_only.js
  - url: /local/monster-card/monster-card.js
    type: js
#background: center / cover no-repeat url("/background.png") fixed

views:
  - title: Home
    id: Home
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - id: 2966910d84bb419095fc3bad884daf8c  # Automatically created id
        type: glance
        entities:
          - sensor.current_version
          - sensor.anet
          - sensor.uptime
          - updater.updater
          - input_boolean.sleeping
          - input_boolean.streaming
          - entity: sensor.phonebatt
            name: Zeus
          - entity: sensor.watchbatt
            name: Chronos
      - id: 4983d29f16f943a5b3d8306b3d5c9f76  # Automatically created id
        type: entity-filter
        entities:
#          - device_tracker.zeus_router
#          - device_tracker.owntracks_zeu
          - device_tracker.apollo
          - device_tracker.hades
          - device_tracker.poseidon
        state_filter:
          - home
        card:
          type: glance
          title: Who is home?
          show_state: false

      - id: b3f6f92e2a7e4bb0aed9aa238bf6099e  # Automatically created id
        type: entities
        title: Alarm Primer
        entities:
          - entity: input_datetime.alarm
            name: Alarm Time
          - input_boolean.alarmstatus
        show_header_toggle: false
      - id: 2d5ea873b38f4dff879d3fb93cebbdee  # Automatically created id
        type: entities
        entities:
          - entity: switch.hades
            icon: mdi:desktop-classic
        title: Wake on LAN
        show_header_toggle: false
      - id: Lights
        type: entities
        entities:
          - light.living_room
          - light.hallway
          - light.extended_color_light_1
        title: Lights
      - id: Temperatures
        type: entities
        entities:
          - entity: sensor.yr_temperature
            name: Outside
          - entity: sensor.living_room_sensor_temperature
            name: Livingroom
          - entity: sensor.hallway_sensor_temperature
            name: Hallway
        title: Temperatures
        show_header_toggle: false
      - type: custom:monster-card
        card:
          type: entities
          title: Tracking
          show_header_toggle: false
        show_empty: true
        filter:
          include:
           - entity_id: 'sensor.*track_package_*'
             options:
               secondary_info: last-changed
#      - id: 2be24faf8d354507ae60bb0eeb5a49fd  # Automatically created id
#        type: entities
#        entities:
#          - input_boolean.testing
  - id: 1  # Automatically created id
    icon: mdi:sofa
    background: radial-gradient(crimson, skyblue)
    title: Living room
    cards:
      - id: 66deab68c74642b49ec6d2ad24bc6ee7  # Automatically created id
        type: custom:group-card
        card:
          type: entities
          title: Lights
        group: group.livingroom_lights
      - id: 24dedaa8f7954ca0b785b69af7a738db  # Automatically created id
        type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: input_boolean.hjuul
          - type: history-graph
            entities:
              - sensor.living_room_sensor_light_level
            hours_to_show: 24
          - type: entities
            title: Temperature
            show_header_toggle: false
            entities: 
              - sensor.living_room_sensor_temperature
          - type: history-graph
            entities:
              - sensor.living_room_sensor_temperature
            hours_to_show: 168
          - type: entities
            entities: 
              - binary_sensor.living_room_sensor_motion
            name: Motion
            accuracy: 24

  - id: 2  # Automatically created id
    icon: mdi:bed
    background: radial-gradient(crimson, skyblue)
    title: Bed room
    cards:
      - id: 10659dff68d7451d9056732335ecf9cb  # Automatically created id
        type: custom:group-card
        card:
          type: entities
          title: Lights
        group: group.hallway_lights
      - id: 9efe6b505d0d474a9d3b840daf61939a  # Automatically created id
        type: vertical-stack
        cards:
          - type: history-graph
            entities:
              - sensor.hallway_sensor_light_level
            hours_to_show: 24
          - type: entities
            title: Temperature
            show_header_toggle: false
            entities: 
              - sensor.hallway_sensor_temperature
          - type: history-graph
            entities:
              - sensor.hallway_sensor_temperature
            hours_to_show: 168
          - type: entities
            entities: 
              - binary_sensor.living_room_sensor_motion
            name: Motion
            accuracy: 24

  - id: 3  # Automatically created id
    icon: mdi:fridge
    background: radial-gradient(crimson, skyblue)
    title: Living Room
    cards:
      - id: c4a4a06c0d284054912096169ca50da9  # Automatically created id
        type: entities
        entities:
          - switch.flakt
          # - sensor.kitchen_plug_amps
          # - sensor.kitchen_plug_volts
          # - sensor.kitchen_plug_watts
          # - sensor.kitchen_plug_today_kwh
          # - sensor.kitchen_plug_total_kwh

  - id: 4  # Automatically created id
    icon: mdi:play-pause
    background: radial-gradient(crimson, skyblue)
    title: Media
    cards:
      - id: 3e1b543875364b20b86e896979dbec94  # Automatically created id
        type: vertical-stack
        title: Spotify
        cards:
          - type: media-control
            entity: media_player.spotify
          - type: entities
            entities:
              - input_select.spotify_playlist
              - input_select.spotify_source
              - script.spotify_music
              - input_boolean.spotify_shuffle
              - input_number.spotify_volume

      #- type: media-control
      #  entity: media_player.shield
      - id: dd0b5d697dfa480bb9836c76aabed5ce  # Automatically created id
        type: vertical-stack
        cards:
          - type: entities
            title: Media Supervising
            show_header_toggle: false
            entities:
              - entity: sensor.sonarr_series
                name: Sonarr
              - entity: sensor.radarr_movies
                name: Radarr
              - entity: sensor.sonarr_wanted
                name: Wanted
              - entity: sensor.sonarr_upcoming
                name: Upcoming
              - entity: sensor.radarr_upcoming
                name: Upcoming
              - entity: sensor.sonarr_queue
                name: Queue
              - entity: sensor.transmission_status
                name: Status
          - type: entities
            title: Transmission Info 
            show_header_toggle: false
            entities:
              - entity: sensor.transmission_total_torrents
                name: Total
              - entity: sensor.transmission_active_torrents
                name: Active
              - entity: sensor.transmission_completed_torrents
                name: Completed
            hours_to_show: 24
          - type: history-graph
            title: Up/Down Speed
            entities:
              - entity: sensor.transmission_down_speed
                name: Down
              - entity: sensor.transmission_up_speed
                name: Up
            hours_to_show: 24
          

  - id: 5  # Automatically created id
    icon: mdi:temperature-celsius
    background: radial-gradient(crimson, skyblue)
    title: Temperature
    panel: false
    cards:
    # - type: horizontal-stack
      # cards:
      # - type: vertical-stack
        # cards:
    # - type: markdown
      # content: >
        # <h1><center>Prognosis
    # - type: vertical-stack
      # cards:
      # - type: horizontal-stack
        # cards:
    # - type: vertical-stack
      # cards:
      # - type: markdown
        # content: >
          # <h2><center>Yahoo
      # - type: 'custom:weather-card'
        # entity_weather: weather.yweather
        # entity_sun: sun.sun
#      - id: 1a790fc6e5c042e3aae38776548272de  # Automatically created id
      -  type: vertical-stack
         cards:
           - type: markdown
             content: >
               <h2><center>SMHI
           - type: 'custom:weather-card-chart'
             weather: weather.hourly_owm
             title: Linköping
             mode: hourly
             chartOnly: false
           - type: 'custom:weather-card-chart'
             weather: weather.daily_owm
             ##title: Linköping
             mode: daily
             chartOnly: true
             #sun: sun.sun
          
            

    # - type: vertical-stack
      # cards:
      # - type: markdown
        # content: >
          # <h2><center>Yr
      # - type: glance
        # entities:
        # - sensor.yr_temperature
        # - entity: sensor.yr_precipitation
          # icon: mdi:weather-rainy
        # #- sensor.yr_wind_speed
        # - sensor.yr_pressure
        # #- sensor.yr_wind_direction
        # - entity: sensor.yr_humidity
          # icon: mdi:water
        # - entity: sensor.yr_fog
          # icon: mdi:weather-fog
        # - entity: sensor.yr_cloudiness
          # icon: mdi:weather-cloudy
        # #- sensor.yr_low_clouds
        # #- sensor.yr_medium_clouds
        # #- sensor.yr_high_clouds
        # - entity: sensor.yr_dewpoint_temperature
          # name: Dewpoint
        # - sun.sun
        # column_width: 33%
          #- type: picture
           # image: https://www.yr.no/sted/Sverige/%C3%96sterg%C3%B6tland/Link%C3%B6ping/meteogram.svg



  - id: 6  # Automatically created id
    icon: mdi:lan
    background: radial-gradient(crimson, skyblue)
    title: Server info
    cards:
      #Netdata
      - id: 7b90f3f63a674c9883588e41042da35d  # Automatically created id
        type: vertical-stack
        cards:
          - type: markdown
            content: >
              <center><h1> Netdata </h1></center>
          #- type: gauge
          #  title: Load 15
          #  entity: sensor.netdata_load15
          #  unit_of_measurement: " "
          #- type: gauge
          #  title: System CPU
          #  entity: sensor.netdata_cpu
          #- type: entities
          #  title: RAM
          #  entities:
          #    - entity: sensor.netdata_freeram
          #      name: Free
          #    - entity: sensor.netdata_usedram
          #      name: Used
          #    - entity: sensor.netdata_cachedram
          #      name: Cashed
          #- type: entities
          #  title: Free Disk Space
          #  entities:
          #    - entity: sensor.netdata_boot
          #      name: Boot
          #    - entity: sensor.netdata_media
          #      name: Media
          #    - entity: sensor.netdata_cloud
          #      name: Cloud

      #Internet stuff
      - id: af24b6853bce48ae937356c8500ca20f  # Automatically created id
        type: vertical-stack
        cards:
          # - type: sensor
          #   entity: sensor.rt_ac1200g_kbyte_sec_received
          #   name: Bytes Received
          #   accuracy: 24
          # - type: sensor
          #   entity: sensor.rt_ac1200g_kbyte_sec_sent
          #   name: Bytes Sent
          #   accuracy: 24
          - type: picture-elements
            image: /local/lovelace/Home/isp_4.png
            #title: Internet
            elements:
              - type: state-icon
                entity: sensor.speedtest_ping
                style:
                  top: 85%
                  left: 25%

              - type: state-label
                entity: sensor.speedtest_ping
                prefix: "Speedtest : "
                style:
                  top: 93%
                  left: 20%
                  font-size: 115%
                  font-weight: bold

              - type: state-icon
                entity: sensor.speedtest_download
                style:
                  top: 85%
                  left: 50%

              - type: state-label
                entity: sensor.speedtest_download
                style:
                  top: 93%
                  left: 50%
                  font-size: 115%
                  font-weight: bold

              - type: state-icon
                entity: sensor.speedtest_upload
                style:
                  top: 85%
                  left: 75%

              - type: state-label
                entity: sensor.speedtest_upload
                style:
                  top: 93%
                  left: 75%
                  font-size: 115%
                  font-weight: bold

  - id: 7  # Automatically created id
    icon: mdi:rocket
    background: radial-gradient(crimson, skyblue)
    title: SpaceX
    cards:
      - id: f93c58b5770b40cb9fa7e206dc3aa9de  # Automatically created id
        type: entities
        title: SpaceX
        entities:
          - sensor.starman_speed
          - sensor.starman_earth_distance
          - sensor.spacex_next_rocket
          - sensor.spacex_next_mission_name
          - sensor.spacex_next_launch_day
          - sensor.spacex_next_launch_time
          - sensor.spacex_next_launch_site
          - automation.rocket_launch

  - id: 8  # Automatically created id
    title: SMHI
    cards:
      - id: fbc688989364421593287ccbccf13bed  # Automatically created id
        type: vertical-stack
        cards:
          - type: markdown
            content: >
              <center><h1> SMHI - Season and temp last 30 days </h1></center>
          - type: entities
            entities:
              - entity: sensor.season_checker
                name: Current season
              - input_datetime.season_date
              - entity: sensor.season_days
                name: Days since season changed
                icon: mdi:calendar
              - entity: sensor.mean_temp
                name: Yesterday's meantemperature
                icon: mdi:thermometer
          - type: history-graph
            entities:
              - sensor.mean_temp
            hours_to_show: 8760 
            title: "365 days"
          - type: history-graph
            entities:
              - sensor.mean_temp
            hours_to_show: 168
            title: "7 days"
  - id: 9  # Automatically created id
    title: Automatron
    cards:
      - id: d7468ca973b0416f981bd2a5e214c359  # Automatically created id
        type: custom:group-card
        card:
          type: entities
          title: All automations
        group: group.all_automations




