title: ANet Homeassistant
# Include external resources
resources:
#  - url: /local/my-custom-card.js
#    type: js
#  - url: /local/my-webfont.css
#    type: css
  - url: /local/custom_ui/weather-card.js
    type: js
  - url: /local/group-card/group-card.js
    type: js

#background: center / cover no-repeat url("/background.png") fixed

views:
  - title: Home
    id: Home
    background: radial-gradient(crimson, skyblue)
    theme: dark-mode
    cards:
      - type: glance
        entities:
          - sensor.current_version
          - sensor.anet
          - sensor.uptime
          - updater.updater
          - entity: sensor.phonebatt
            name: Zeus
          - entity: sensor.watchbatt
            name: Chronos
      - type: glance
        title: Who is home?
        entities:
          - device_tracker.zeus
          - device_tracker.hades
          - device_tracker.poseidon
            
      - type: entities
        title: Alarm Primer
        entities: 
          - entity: input_datetime.input_time
            name: Alarm Time
          - input_boolean.alarmstatus
        show_header_toggle: false
      - type: entities
        entities: 
          - entity: switch.hades
            icon: mdi:desktop-classic
        title: Wake on LAN
        show_header_toggle: false
  - icon: mdi:sofa
    title: Living Room
    cards:
      - type: horizontal-stack
        cards:
          - type: vertical-stack
            title: Livingroom
            cards:
              - type: markdown
                content: >
                    <center><h1> Livingroom </h1></center>
              - type: sensor
                entity: sensor.living_room_light
                name: Light Level
                accuracy: 24
              - type: sensor
                entity: sensor.living_room_temperature
                name: Temperature
                accuracy: 24
          - type: vertical-stack
            title: Hallway
            cards:
              - type: markdown
                content: >
                    <center><h1> Hallway </h1></center>
              - type: sensor
                entity: sensor.hallway_light
                name: Light Level
                accuracy: 24
              - type: sensor
                entity: sensor.hallway_temperature
                name: Temperature
                accuracy: 24
          
      - type: entities
        title: Lights
        entities: 
          - entity: light.living_room
            icon: mdi:power
            name: Livingroom
          - entity: light.hue_white_lamp_1
            icon: mdi:power
            name: Hallway
        show_header_toggle: false        
          
  - icon: mdi:play-pause
    title: Media
    cards:
      - type: vertical-stack
        title: Spotify
        cards:
          - type: media-control
            entity: media_player.spotify
          - type: entities
            entities:
            - input_select.spotify_playlist
            - input_select.spotify_source
            - script.spotify_music
            - input_boolean.spotify_shuffle
            - input_number.spotify_volume
          
          
      
        
      - type: media-control
        entity: media_player.shield
               
  - icon: mdi:temperature-celsius
    # Title of the view. Will be used as the tooltip for tab icon
    title: Temperature
    cards:
        # Entities card will take a list of entities and show their state.
      - type: glance
        # Title of the entities card
        title: Outside Weather Data
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - sensor.yr_temperature
          - sensor.yr_precipitation
          #- sensor.yr_wind_speed
          - sensor.yr_pressure
          #- sensor.yr_wind_direction
          - sensor.yr_humidity
          - sensor.yr_fog
          - sensor.yr_cloudiness
          #- sensor.yr_low_clouds
          #- sensor.yr_medium_clouds
          #- sensor.yr_high_clouds
          - sensor.yr_dewpoint_temperature
          - sun.sun
          - sensor.season
          
    #  - type: weather-forecast
    #    entity: weather.yweather
    #    title: Forecast
      
      - type: 'custom:weather-card'
        entity_weather: weather.yweather
        entity_sun: sun.sun
        
      - type: picture
        image: https://www.yr.no/sted/Sverige/%C3%96sterg%C3%B6tland/Link%C3%B6ping/meteogram.svg
        
  - icon: mdi:server-network
    title: Server info
    cards:
      #Netdata
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              <center><h1> Netdata </h1></center>
          - type: gauge
            title: Load 15
            entity: sensor.netdata_load15
            unit_of_measurement: " "
          - type: gauge
            title: System CPU
            entity: sensor.netdata_cpu
          - type: entities
            title: RAM
            entities:
              - entity: sensor.netdata_freeram
                name: Free
              - entity: sensor.netdata_usedram
                name: Used
              - entity: sensor.netdata_cachedram
                name: Cashed
          - type: entities
            title: Free Disk Space 
            entities:
              - entity: sensor.netdata_boot
                name: Boot
              - entity: sensor.netdata_media
                name: Media
              - entity: sensor.netdata_cloud
                name: Cloud
          
      #Internet stuff
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.rtac1200g_kbytesec_received
            name: Bytes Received
            accuracy: 24
          - type: sensor
            entity: sensor.rtac1200g_kbytesec_sent
            name: Bytes Sent
            accuracy: 24
          - type: picture-elements
            image: /local/lovelace/Home/isp_4.png
            #title: Internet
            elements:
            - type: state-icon
              entity: sensor.speedtest_ping
              style:
                top: 85%
                left: 25%
                
            - type: state-label 
              entity: sensor.speedtest_ping
              prefix: "Speedtest : " 
              style:
                top: 93%
                left: 20%
                font-size: 115%
                font-weight: bold
                
            - type: state-icon
              entity: sensor.speedtest_download
              style:
                top: 85%
                left: 50%
                
            - type: state-label 
              entity: sensor.speedtest_download
              style:
                top: 93%
                left: 50%
                font-size: 115%
                font-weight: bold
                
            - type: state-icon
              entity: sensor.speedtest_upload
              style:
                top: 85%
                left: 75%
               
            - type: state-label 
              entity: sensor.speedtest_upload
              style:
                top: 93%
                left: 75%
                font-size: 115%
                font-weight: bold
         
  - icon: mdi:rocket
    title: SpaceX
    cards:
      - type: entities
        title: SpaceX
        entities:
          - sensor.starman_speed
          - sensor.starman_earth_distance
          - sensor.spacex_next_rocket
          - sensor.spacex_next_mission_name
          - sensor.spacex_next_launch_day
          - sensor.spacex_next_launch_time
          - sensor.spacex_next_launch_site
          - automation.rocket_launch
  
  - icon: mdi:home
    title: Automatron
    cards:
      - type: custom:group-card
        card:
          type: entities
          title: All automations
        group: group.all_automations
        
        